# Generated by Django 4.2.13 on 2024-07-08 10:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
        ('search_terms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=4096, unique=True, verbose_name='job id')),
                ('url', models.URLField(verbose_name='url')),
                ('published_date', models.DateTimeField(verbose_name='published date')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
        ),
        migrations.CreateModel(
            name='JobSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_skills', to='jobs.job')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_skills', to='skills.skill')),
            ],
        ),
        migrations.CreateModel(
            name='JobSearchTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_search_terms', to='jobs.job')),
                ('search_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_search_terms', to='search_terms.searchterm')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='search_terms',
            field=models.ManyToManyField(related_name='jobs', through='jobs.JobSearchTerm', to='search_terms.searchterm'),
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(related_name='jobs', through='jobs.JobSkill', to='skills.skill'),
        ),
    ]
