# Generated by Django 4.2.13 on 2024-07-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='url',
            field=models.CharField(max_length=4000, verbose_name='url'),
        ),
    ]
