# Generated by Django 4.2.13 on 2024-07-19 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='budget_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='budget amount'),
        ),
        migrations.AddField(
            model_name='job',
            name='budget_max_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='budget max rate'),
        ),
        migrations.AddField(
            model_name='job',
            name='budget_min_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='budget min rate'),
        ),
        migrations.AddField(
            model_name='job',
            name='budget_type',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('hourly', 'Hourly'), ('hourly_range', 'Hourly Range'), ('not_specified', 'Not Specified')], default='not_specified', max_length=50, verbose_name='budget type'),
        ),
    ]
